openapi: 3.0.1
info:
  title: DataFormAPI
  description: API Definition of DataFormAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/file
paths:
  /:
    get:
      responses:
        default:
          description: Default response
