openapi: 3.0.1
info:
  title: DocumentClassification
  description: API Definition of DocumentClassification
  version: 1.0.0
servers:
- url: http://localhost:8290/document
paths:
  /classify/startJob:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /classify/describe:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
