openapi: 3.0.1
info:
  title: FileAPI
  description: API definition
  version: 1.0.0
servers:
- url: http://localhost:8290/files
paths:
  /upload:
    post:
      requestBody:
        description: Sample Payload
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadFile'
        required: false
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFileResponse'
  /download/{docId}:
    get:
      parameters:
      - name: docId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
components:
  schemas:
    UploadFile:
      required:
      - fileContent
      type: object
      properties:
        fileContent:
          type: string
          format: binary
        subPath:
          type: string
          format: string
          example: projectA/2023
    UploadFileResponse:
      type: object
      properties:
        file:
          type: string
          example: sample.pdf
        status:
          type: string
          example: File upload sucessfully
