openapi: 3.0.1
info:
  title: FileAPI
  description: API definition
  version: 1.0.0
servers:
- url: http://localhost:8290/files
paths:
  /upload:
    post:
      requestBody:
        description: Sample Payload
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadFile'
        required: false
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFileResponse'
  /download/{docId}:
    post:
      parameters:
      - name: docId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /uploadSftp:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/form-data:
            schema:
              $ref: '#/components/schemas/LocalFileScanRequest'
        required: false
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalToSFTPResponse'
  /uploadObjectStorage:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/form-data:
            schema:
              $ref: '#/components/schemas/LocalFileToObjectStorageReq'
      responses:
        default:
          description: Default response
components:
  schemas:
    UploadFile:
      required:
      - fileContent
      type: object
      properties:
        fileContent:
          type: string
          format: binary
        subPath:
          type: string
          format: string
          example: projectA/2023
    UploadFileResponse:
      type: object
      properties:
        file:
          type: string
          example: sample.pdf
        status:
          type: string
          example: File upload sucessfully
    LocalFileScanRequest:
      type: object
      properties:
        dir:
          type: string
          description: It's relative path to the workingDir defined in LOCAL_FILE_DIR
            local entry
          example: /Users/john/Downloads/FileStore/Source
        filePattern:
          type: string
          example: .*.pdf
    LocalToSFTPResponse:
      type: object
      properties:
        file:
          type: string
          example: /Users/john/Downloads/FileStore/Source/abc.pdf
        uploadSuccessful:
          type: boolean
          example: true
        archiveSuccessful:
          type: boolean
          example: true
    LocalFileToObjectStorageReq:
      type: object
      properties:
        localDir:
          type: string
          description: It's relative path to the workingDir defined in LOCAL_FILE_DIR
            local entry
          example: /Users/john/Downloads/FileStore/Source
        filePattern:
          type: string
          example: .*.pdf
        bucket:
          type: string
          example: project
        osDir:
          type: string
          description: The directory on Object Storage to which the file will be uploaded
          example: /test/2023/12
        topic:
          type: string
          description: The kafka topic to which the message will be published
          example: upload-events
