openapi: 3.0.1
info:
  title: FileAPI
  description: API definition
  version: 1.0.0
servers:
- url: http://localhost:8290/files
paths:
  /upload:
    post:
      requestBody:
        description: Sample Payload
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
