openapi: 3.0.1
info:
  title: ImageReceivingAPI
  description: API Definition of ImageReceivingAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/images
paths:
  /:
    post:
      responses:
        default:
          description: Default response
