openapi: 3.0.1
info:
  title: IdGeneratorAPI
  description: API Definition of IdGeneratorAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/sequence
paths:
  /{sequenceId}/{action}:
    get:
      parameters:
      - name: sequenceId
        in: path
        required: true
        schema:
          type: string
      - name: action
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
