openapi: 3.0.1
info:
  title: CloneSFTPFileAPI
  description: API Definition of CloneSFTPFileAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/files
paths:
  /list:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /clone:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
